# -*- coding: utf-8 -*-
"""tcp_echo_client.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1XN00VkrDyXTah4V4ZTeUboh0f41AACUl

#TCP Echo Client
"""

import socket

#Define the Server Host (ip address) and Server Port Number(greater than 1024) of your Choice

srvr_host='10.114.27.246'
srvr_port=35791

#Create a Socket boject using socket() method and pass the ip Socket and the tcp socket inside the method as arguments

client_socket=socket.socket(socket.AF_INET,socket.SOCK_STREAM)

#Now Initiate the Connection (Connect to the server) by using connect() method and pass the srvr_host, srvr_port as parameters to this method

client_socket.connect((srvr_host,srvr_port))

#Now We need to Send the Data to the Server

msg="Heyya! Successfully Connected to the Server!"
client_socket.sendall(msg.encode())  #eEncode the Message

#Now Receive the Data from the Server

rcvd_data=client_socket.recv(1024)
print("Received:",rcvd_data.decode())  #Decode the Message

#Now Connection needs to be Closed by using close() method

client_socket.close()